---
- name: Install prerequisite packages (RHEL family)
  ansible.builtin.command: dnf install -y curl tar which
  when: ansible_facts['os_family'] == 'RedHat'
  register: _dnf_install_result
  changed_when: "'Nothing to do' not in _dnf_install_result.stdout"

- name: Install prerequisite packages (Debian family)
  ansible.builtin.apt:
    name:
      - curl
      - tar
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == 'Debian'